config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  get "customers/alphabetized"
  get "customers/missing_email"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :full_name, :phone_number, presence: true
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.all.order(full_name: :asc)
  end

  def missing_email
    @customers = Customer.where(email_address: "")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_cards.html.erb
<div class="columns">
    <% @customers.each do |customer| %>
      <div class="column">
        <%# Is this the best way to get a view scoped variable to a partial? Would it be better practice to avoid this? %>
        <%= render partial: "customers/customer", object: customer %>
      </div>
    <% end %>
  </div>

app/views/customers/_customer.html.erb
<div class="card">
  <div class="card-header">
    <div class="card-header-title">
      <p><%=customer.full_name%></p>
    </div>
  </div>
  <% if customer.image.present? %>
    <div class="card-image">
      <figure class="image is-4by3">
        <%= image_tag customer.image, alt: "profile picture" %>
      </figure>
    </div>
    <div class="card-content">
      <div class="content">
        <p><b>Phone Number:</b> <%=customer.phone_number%></p>
        <% if customer.email_address.present? %>
          <p><b>Email:</b> <%=customer.email_address%></p>
        <% end %>
        <p><b>Notes:</b> <%=customer.notes%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/customers/_nav.html.erb
<h2 class="subtitle"><%= link_to "Index", root_path() %> | <%= link_to "Alphabetized", customers_alphabetized_path() %> | <%= link_to "Missing Emails", customers_missing_email_path() %></h2>

app/views/customers/alphabetized.html.erb
<div class="mr-4 ml-4">
  <h1 class="title">Alphabetized Customers</h1>
  <%= render "customers/nav" %>
  <%= render "customers/cards" %>
</div>

app/views/customers/index.html.erb
<div class="mr-4 ml-4">
  <h1 class="title">All Customers</h1>
  <%= render "customers/nav" %>
  <%= render "customers/cards" %>
</div>

app/views/customers/missing_email.html.erb
<div class="mr-4 ml-4">
  <h1 class="title">Customers Missing Email</h1>
  <%= render "customers/nav" %>
  <%= render "customers/cards" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>